import Head from "next/head";
import Image from "next/image";
import Body from "../components/body";
import AboutUs from "../components/about_us";
import Services from "../components/services";
import Sendmail from "../components/sendmail";
import Works from "../components/works";
import Footer from "../components/footer";
import Navnew from "../components/navbar2";
import WhyUS from "../components/WhyUs";
import Testimonials from "../components/Testimonials";
// import EmailPra from "../components/emailPra";
import ButtonMailto from "../components/emailPra";

export default function Home() {
  return (
    <div className="m-0">
      <Navnew />
      {/* <Navbar /> */}
      <Body></Body>
      <AboutUs></AboutUs>
      <Services />

      <Works />
      <WhyUS />
      <Testimonials />
      <Sendmail />
      <Footer />
      <Head>
        <title>Estate app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
